# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3728fdee80d448499945b3dd107488540a1aae3661ccdcdb1eb1b74b78b1c39a5bc9f353c502c720f288610a5944f6d22c594a53d9b4c6fb77fdb5148dd6aef3

test:
  secret_key_base: 25c92cba86231640847bbcff6934412c3e13deb24e207296ae09bbedb624726fe267600f24c7a89c8c5f7074516c4b5e3610a9d5f0600e88a64f50e8f08764a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
